package com.paynest.exception;

import org.springframework.http.HttpStatus;

public enum PaymentErrorCode implements CatalogErrorCode {
    OPERATION_TYPE_MISSING(HttpStatus.BAD_REQUEST),
    OPERATION_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    REQUEST_GATEWAY_MISSING(HttpStatus.BAD_REQUEST),
    INITIATED_BY_MISSING(HttpStatus.BAD_REQUEST),
    DEBTOR_MISSING(HttpStatus.BAD_REQUEST),
    CREDITOR_MISSING(HttpStatus.BAD_REQUEST),
    WALLET_TYPE_MISSING(HttpStatus.BAD_REQUEST),
    IDENTIFIER_MISSING(HttpStatus.BAD_REQUEST),
    IDENTIFIER_TYPE_MISSING(HttpStatus.BAD_REQUEST),
    IDENTIFIER_VALUE_MISSING(HttpStatus.BAD_REQUEST),
    AUTHENTICATION_REQUIRED(HttpStatus.BAD_REQUEST),
    AUTH_TYPE_MISSING(HttpStatus.BAD_REQUEST),
    AUTH_VALUE_MISSING(HttpStatus.BAD_REQUEST),
    TRANSACTION_MISSING(HttpStatus.BAD_REQUEST),
    INVALID_AMOUNT(HttpStatus.BAD_REQUEST),
    INVALID_AMOUNT_SCALE(HttpStatus.BAD_REQUEST),
    PAYMENT_REFERENCE_TOO_LONG(HttpStatus.BAD_REQUEST),
    COMMENTS_TOO_LONG(HttpStatus.BAD_REQUEST),
    CURRENCY_MISSING(HttpStatus.BAD_REQUEST),
    INVALID_CURRENCY(HttpStatus.BAD_REQUEST),
    SELF_TRANSFER_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    INVALID_DEBITOR_USER_TYPE(HttpStatus.BAD_REQUEST),
    INVALID_CREDITOR_USER_TYPE(HttpStatus.BAD_REQUEST),
    INVALID_CREDITOR_IDENTIFIER_TYPE(HttpStatus.BAD_REQUEST),
    BILL_PAYMENT_STATUS_MISSING(HttpStatus.BAD_REQUEST),
    INVALID_BILL_PAYMENT_STATUS(HttpStatus.BAD_REQUEST),
    BILL_PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    BILL_PAYMENT_ALREADY_SETTLED(HttpStatus.BAD_REQUEST),
    INVALID_BILL_PAYMENT_TRANSACTION(HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    INVALID_PRIVILEGES(HttpStatus.FORBIDDEN),
    INVALID_DEBITOR_ACCOUNT_TYPE(HttpStatus.BAD_REQUEST),
    INVALID_CREDITOR_ACCOUNT_TYPE(HttpStatus.BAD_REQUEST),
    INVALID_INITIATOR(HttpStatus.BAD_REQUEST),
    CROSS_WALLET_TRANSFER_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    TRACE_ID_MISSING(HttpStatus.BAD_REQUEST),
    SETTLEMENT_STATUS_MISSING(HttpStatus.BAD_REQUEST),
    TRANSACTION_TRACE_NOT_FOUND(HttpStatus.NOT_FOUND),
    TRANSACTION_NOT_PENDING_SETTLEMENT(HttpStatus.BAD_REQUEST),
    INVALID_TRANSACTION_DETAILS(HttpStatus.BAD_REQUEST),
    INSUFFICIENT_FIC_BALANCE(HttpStatus.BAD_REQUEST),
    INSUFFICIENT_CREDITOR_BALANCE(HttpStatus.BAD_REQUEST),
    ACCOUNT_IDENTIFIER_NOT_FOUND(HttpStatus.BAD_REQUEST),
    ACCOUNT_NOT_FOUND(HttpStatus.BAD_REQUEST),
    WALLET_NOT_FOUND(HttpStatus.BAD_REQUEST),
    INVALID_WALLET(HttpStatus.BAD_REQUEST),
    WALLET_LOCKED(HttpStatus.BAD_REQUEST),
    WALLET_SEND_BLOCKED(HttpStatus.BAD_REQUEST),
    WALLET_RECEIVE_BLOCKED(HttpStatus.BAD_REQUEST),
    INVALID_AUTH_TYPE(HttpStatus.BAD_REQUEST),
    ACCOUNT_AUTH_NOT_FOUND(HttpStatus.BAD_REQUEST),
    ACCOUNT_AUTH_INACTIVE(HttpStatus.BAD_REQUEST),
    ACCOUNT_LOCKED(HttpStatus.BAD_REQUEST),
    INVALID_PIN(HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(HttpStatus.BAD_REQUEST),
    INSUFFICIENT_BALANCE(HttpStatus.BAD_REQUEST),
    INSUFFICIENT_FROZEN_BALANCE(HttpStatus.BAD_REQUEST),
    WALLET_BALANCE_NOT_FOUND(HttpStatus.BAD_REQUEST),
    INVALID_PRE_AUTH_HOLD_REQUEST(HttpStatus.BAD_REQUEST),
    PRE_AUTH_HOLD_ALREADY_EXISTS(HttpStatus.BAD_REQUEST),
    PRE_AUTH_HOLD_NOT_FOUND(HttpStatus.NOT_FOUND),
    PRE_AUTH_HOLD_NOT_ACTIVE(HttpStatus.BAD_REQUEST),
    PRE_AUTH_DECREMENT_EXCEEDS_HOLD(HttpStatus.BAD_REQUEST),
    UNREGISTERED_PAYEE_ALREADY_EXISTS(HttpStatus.BAD_REQUEST),
    PASSCODE_NOT_FOUND(HttpStatus.NOT_FOUND),
    PASSCODE_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    QR_PAYLOAD_MISSING(HttpStatus.BAD_REQUEST),
    QR_PAYLOAD_INVALID(HttpStatus.BAD_REQUEST),
    QR_INTENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    QR_INTENT_EXPIRED(HttpStatus.BAD_REQUEST),
    QR_INTENT_ALREADY_USED(HttpStatus.BAD_REQUEST),
    QR_PAYMENT_TYPE_NOT_SUPPORTED(HttpStatus.BAD_REQUEST),
    QR_AMOUNT_REQUIRED(HttpStatus.BAD_REQUEST),
    QR_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus httpStatus;

    PaymentErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    @Override
    public String code() {
        return name();
    }

    @Override
    public HttpStatus httpStatus() {
        return httpStatus;
    }
}
